[package]
name = "freya-material"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { git = "https://github.com/marc2332/freya.git", branch = "feat/dioxus-0.6" }
freya-transition = { path = "../freya-transition" }
material-colors = "0.4.2"
material-icons = { git = "https://github.com/Aiving/material-icons.git" }
once_cell = "1.20.2"
